# Generated by Django 4.2 on 2024-08-17 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_rename_unit_price_product_purchase_detail_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_detail',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Mal estado', 'Mal estado'), ('Nuevo', 'Nuevo')], max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.product'),
        ),
    ]
