# Generated by Django 4.2 on 2024-08-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_remove_purchase_detail_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Mal estado', 'Mal estado')], max_length=30),
        ),
    ]
