# Generated by Django 4.2 on 2024-08-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Usado', 'Usado'), ('Nuevo', 'Nuevo'), ('Mal estado', 'Mal estado')], max_length=30),
        ),
    ]
